{
 "title": "VLLM Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Habana Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "habanalabs_energy{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Habana Power mW (used, limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "habanalabs_power_mW{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "habanalabs_power_default_limit_mW{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Habana Memory (Free, Used, Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "habanalabs_memory_free_bytes{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "habanalabs_memory_total_bytes{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "habanalabs_memory_used_bytes{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (onboard, onchip)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "habanalabs_temperature_onboard{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "habanalabs_temperature_onchip{pod_namespace=\"inference-benchmark-tool\", pod_name=\"inference-vllm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\", container!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\", resource=\"cpu\"}\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\",  namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\", resource=\"cpu\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\", resource=\"memory\"}\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"inference-benchmark-tool\", pod=\"inference-vllm\", resource=\"memory\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"inference-benchmark-tool\", pod=~\"inference-vllm\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"inference-benchmark-tool\", pod=~\"inference-vllm\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"inference-benchmark-tool\", pod=~\"inference-vllm\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"inference-benchmark-tool\", pod=~\"inference-vllm\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}